### PR TITLE
Fix logged group name in reinforcement check

### PR DESCRIPTION
**Pull request by Haxx0r-4559**
Untested, but a very simple correction.

### CODE REVIEW

**Comment by Diet-Cola** [comment]
Hi there,

Thank you for contributing! Can you post a screenshot of what the current message is?

**Comment by Haxx0r-4559** [comment]
When in CTR mode with a selected group (in this example, `Mta-infra`), clicking a block already reinforced on another group lets a player update its group. However, if the player lacks reinforcement permissions on the group which the block is already reinforced on, the following message is sent:

ctr_message

This message is inaccurate, as the group I don't have permission to bypass is the one which the block is reinforced on, not my currently selected CTR group.

**Comment by Diet-Cola** [comment]
Excellent find, thank you

**Comment by Diet-Cola** [comment]
Well actually we wouldn't want to expose the group at all since this would be exposing information that shouldn't be exposed right?

**Comment by Haxx0r-4559** [comment]
That is true. Perhaps the message could be changed to something like "You do not have permission to bypass this reinforcement".

**Pull request merged**
