### PR TITLE
Improve moss spreading check logic

### LINKED ISSUE #12: DRAFT: Handle events like moss spread via dispenser
See discussion on #11

### PR DESCRIPTION
**Pull request by MelnCat**
This improves the moss spreading checks by revamping how the spread blocks are disabled, and allowing dispensers to spread moss to same-group and unreinforced blocks.

Changes:
- Allow dispensers to spread moss either if the dispenser is in the same group as the block, or if the block is unreinforced. Fixes #12 
- Instead of preventing the entire spread when there is a reinforced block nearby, the spreading will simply not spread to inaccessible reinforced blocks, and will only spread to blocks the player has access to.

### CODE REVIEW

**Comment by Diet-Cola** [comment]
Does this definitely fire the BlockFerilizeEvent after the BlockDispenseEvent?

**Comment by MelnCat** [comment]
> Does this definitely fire the BlockFerilizeEvent after the BlockDispenseEvent?

Yes. BlockDispenseEvent is called before the item is dispensed from the dispenser, so the event allows you to modify things such as the item being dispensed from the dispenser, or whether to cancel it.
BlockFertilizeEvent will be called due to the bone meal being dispensed, this is called after BlockDispenseEvent, since the BlockDispenseEvent is called first to check if the dispensed item stays as bone meal, or if it is cancelled.

**Comment by MelnCat** [comment]
I've also tested this fork in a local server, and the changes function properly.

**Comment by MelnCat** [comment]
image
Strange error from the pr check

**Comment by wingzero54** [comment]
@MelnCat sorry I was about to merge and saw it has a conflict now

**Comment by MelnCat** [comment]
Fixed

**Comment by Diet-Cola** [comment]
El rapid

**Pull request merged**
