### PR TITLE
Improve structure (tree) generation integration

### PR DESCRIPTION
**Pull request by MelnCat**
This allows trees to generate even if there are reinforced blocks nearby, but without replacing the reinforced blocks.
Previously, the entire structure would refuse to generate if there was a reinforced block in the way, and the problem was not told to the player. This change fixes that by allowing the structure to still generate, but the reinforced blocks will not be overridden.

### CODE REVIEW

**Review by Aleksey-Terzi — COMMENTED** [review]
Thanks for PR though it looks a bit controversial for me.

1. People will be able to build leaf-based constructions that will make a tree to have the shape they want it to be.
I mean you can put leaves in required locations and make wooden blocks and leaves to be only in places you need it to be.
This will make botting extra simple.

2. "Wooden block auto-drop" feature allows just to cover all area by reinforced leaves and tree will be harvested automatically
No bots needed.

Also some programming issues:

1. We should stay using **civgradle 2**, was there a reason for changing it to **civgralde 1** or is this just a mistake?

2. This line looks like is not required in `onMossSpread` because we just set the event as cancelled
```
if (!event.isCancelled()) CitadelUtility.dropBlockState(block);
```

**Comment by MelnCat** [comment]
That's true, I'll get rid of the dropping part.

> This line looks like is not required in onMossSpread because we just set the event as cancelled

I put that there in case the other pr is added. I'll remove it since I'm getting rid of the dropping part.
I upgraded to civgradle 2 since civgradle 1 failed to reobfuscate the jar when using NMS.

**Comment by Aleksey-Terzi** [comment]
But what do you think about **controversial** points I provided.
In my opinion, it will make producing wood very easy without any specific efforts after the farm is built?
I do not think we want this?

**Comment by MelnCat** [comment]
> But what do you think about **controversial** points I provided. In my opinion, it will make producing wood very easy without any specific efforts after the farm is built? I do not think we want this?

That's a fair point. I don't think it would make producing wood ridiculously easy though, since even if someone was to spam leaf blocks around a tree to get rid of large trees as such, it's already possible with solid blocks. If someone spammed leaf blocks around a 2x2 tree to get rid of branches, it would still be quite a difficult task due to the amount of variance in tree height. A farm made with this wouldn't even be self-sustainable, since it wouldn't produce any saplings.

**Comment by Aleksey-Terzi** [comment]
The player can limit the tree from the top with a roof (as botters do now), put flowing water, hopper(s), reinforced leaves and auto-farm is done, something like can be done for cactuses but now it is for wood.

**Comment by MelnCat** [comment]
A user/bot would still need to mine the wood logs, adding reinforced leaves to the sapling area would only either decrease the amount of logs produced, and/or decrease the amount of leaves produced.

**Comment by MelnCat** [comment]
If you're referring to the "drop blocks that couldn't be placed" part, I removed it a few seconds ago after the first comment.

**Comment by Aleksey-Terzi** [comment]
Yes, I was referring point 2.
Even after removing point 2, we still have point 1.
IMO, that's a pretty serious modification of mechanics which should be first discussed/proposed to admins, either via modmail or #feedback.

**Comment by MelnCat** [comment]
> Yes, I was referring point 2. Even after removing point 2, we still have point 1. IMO, that's a pretty serious modification of mechanics which should be first discussed/proposed to admins, either via modmail or #feedback.

> People will be able to build leaf-based constructions that will make a tree to have the shape they want it to be.
I mean you can put leaves in required locations and make wooden blocks and leaves to be only in places you need it to be.
This will make botting extra simple.

This wouldn't affect botting much, since by placing the leaves, the only impact it would have is either reduce the amount of wood, or reduce the amount of leaves. Reducing the amount of wood isn't something that is typically desired, and reducing the amount of leaves will reduce sapling production, which also isn't desired.

**Comment by wingzero54** [comment]
What is the benefit of making this change? I see a couple issues, some of which aleksey already covers:

- One tree farm method is placing a block above the tree to limit the height variant of tree that spawns. This change would make those trees spawn anyway, making height restrictors on farms not work (if I'm understanding the change properly) 

- I think you underestimate botters, this would definitely be abused for all kinds of custom tree farms. If you're farming saplings, wood is a byproduct. When I was mass farming saplings, I was trying to do my best to limit how much wood spawned, and I would've definitely used something like this to make it so all the trees spawned with less wood. A button on the ground would prevent the first log from spawning, immediately making it easier to bot the trees and save durability if the goal is only sapling production

**Comment by MelnCat** [comment]
> One tree farm method is placing a block above the tree to limit the height variant of tree that spawns. This change would make those trees spawn anyway, making height restrictors on farms not work (if I'm understanding the change properly)

Trees only grow through certain blocks, Citadel wasn't the cause of vanilla tree height limiting.

> I think you underestimate botters, this would definitely be abused for all kinds of custom tree farms. If you're farming saplings, wood is a byproduct. When I was mass farming saplings, I was trying to do my best to limit how much wood spawned, and I would've definitely used something like this to make it so all the trees spawned with less wood. A button on the ground would prevent the first log from spawning, immediately making it easier to bot the trees and save durability if the goal is only sapling production

Hmm, that's true. I'll close this issue since it makes sapling farms too easy.

**Pull request closed without merging**
